### PR TITLE
Only detect focal point for new assets

### LINKED ISSUE #59: Automatic focal point detection should only happen on first save (upload)
As it stands now, there is no way to adjust a focal point if your volume has `autoFocalPoint`, as it is overridden every time.

It really only makes sense to detect on initial creation, so you can adjust it, and so that the Rekognition API doesn't get needlessly called.

### PR DESCRIPTION
**Pull request by timkelty**
Fixes #59

### CODE REVIEW

**Comment by andris-sevcenko** [comment]
❤️

**Comment by timkelty** [comment]
Release pretty please? 👼

**Comment by andris-sevcenko** [comment]
There you go!

**Comment by timkelty** [comment]
🤗

**Pull request merged**
