### PR TITLE
Fix for reading streams in Craft CMS

### PR DESCRIPTION
**Pull request by boboldehampsink**
Fixes bugs in Craft CMS that occurred since https://github.com/thephpleague/flysystem-aws-s3-v3/pull/211

### CODE REVIEW

**Comment by andris-sevcenko** [comment]
Hang on. Are you calling `fseek()` in your custom code or does Craft end up calling it somehow?

**Comment by boboldehampsink** [comment]
Craft calls it on every request that is a stream (via `Response::send`)

**Comment by andris-sevcenko** [comment]
Gotcha.

**Comment by andris-sevcenko** [comment]
Just cut a new release to address this. Opted to use the new argument added in 1.0.28.

**Comment by boboldehampsink** [comment]
Sure! Maybe require at least that version in composer.json then

**Comment by andris-sevcenko** [comment]
Uh, sure? https://github.com/craftcms/aws-s3/commit/2cd433db7c2e4d2a19ffa66c40d78702808ee38b

**Pull request closed without merging**
