### PR TITLE
Use path-based bucket URL default, so we can default to https.

### LINKED ISSUE #34: Use https urls as generated default
By default, it generates a base URL using the virtual-hosted–style url:: http://mybucketname.s3.amazonaws.com/

The default should be https.

Furthermore, by defaulting to the path-based URL, SSL will work no matter what the bucket name is (even if it contains a period "."): https://s3.us-east-1.amazonaws.com/dev.mybucketname/

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

### PR DESCRIPTION
**Pull request by timkelty**
Fixes #34

### CODE REVIEW

**Comment by brandonkelly** [comment]
Guessing this will only work if `$location` is not null.

**Comment by brandonkelly** [comment]
Looks like this will resolve #34

**Comment by timkelty** [comment]
@brandonkelly yeah - it didn't make sense to me why the try/catch was there anyway. Seems like we should throw if the region doesn't come back…updated PR.

**Comment by andris-sevcenko** [comment]
Say you have 50 buckets, but the current project needs only two of those. You would most likely go with an IAM policy like this: https://craftcms.stackexchange.com/a/13870/258

You need the permission to list all the buckets, but only give permission to list everything, including region, only for the few buckets you need. The try/catch block would silently skip the buckets that were not allowed by the policy.

As the PR is now, it would throw an exception for everyone using policy such as that and attempting to select a different bucket.

**Comment by timkelty** [comment]
Thanks @andris-sevcenko, I'll update the PR.

**Comment by timkelty** [comment]
Ok - try/catch is back in with a little note explaining.

**Comment by andris-sevcenko** [comment]
Sweet, thanks!

**Pull request merged**
