### PR TITLE
Stop getFileStream() from transferring the complete file

### PR DESCRIPTION
**Pull request by carlcs**

### CODE REVIEW

**Comment by carlcs** [comment]
Are you still interested in this PR, or do you have any other plans to improve asset indexing performance? I am currently working on a Craft 3 install where we’ll be regularly syncing down hundreds of assets from s3 and would really like to avoid transferring all the GBs of data each time.

**Comment by carlcs** [comment]
Oh, gross… I guess that’s not how you do a rebase? 😱

**Comment by carlcs** [comment]
Better! 😄

**Comment by andris-sevcenko** [comment]
Well, let's not wait for an anniversary for this one :)

**Comment by gijsstegehuis** [comment]
@andris-sevcenko this change breaks asset downloads from CP and transforms via Imager.
Reverting to 1.2.5 fixes this (for now).

**Pull request merged**
